#!/usr/bin/env bash
set -e

help() {
  cat <<EOF
Work seamlessly with GitHub Projects from the command line.

USAGE
  gh projects <command> <subcommand> [flags]

COMMANDS
  list:       List projects owned by user or organization
  view:       View project owned by user or organization by title

FLAGS
  --help, -h  Show help for command

EXAMPLES
  $ gh projects list org
  $ gh projects view user project-title

LEARN MORE
  Use 'gh projects <command> --help' for more information about a command.
  Read the documentation at https://github.com/jnmiller-va/gh-projects
EOF
}

BASEDIR=$(dirname "$0")

if [ $1 == list ] || [ $1 == view ]; then
  command=$1
  shift
  exec $BASEDIR/command/$command.sh "$@"
fi

while [ $# -gt 0 ]; do
  case "$1" in
  -h|--help)
    help
    exit 0
    ;;
  *)
    help >&2
    exit 1
    ;;
  esac
  shift
done